### ISSUE TITLE
download plugins error, please check network!

### ISSUE THREAD

**Issue by xiv3r** [Am0rphous/nessus#1]
Download fail after executing "sudo docker exec -it nessus /bin/bash /nessus/update.sh"

**Comment by Am0rphous** [comment]
What do you mean? I just ran the code without problems. Remember to be patient when waiting for results.

Try stopping and removing the container completely.

**Comment by xiv3r** [comment]
i have internet but i got this error

Seems the download files is missing amd wget unable to get the file from the link

https://plugins.nessus.org/v2/nessus.php?f=all-2.0.tar.gz&u=56b33ade57c60a01058b1506999a2431&p=1ee9c89d5379a119a56498f2d5dff674

Resolving plugins.nessus.org (plugins.nessus.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'plugins.nessus.org'
